import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { geistMono, geistSans } from "@/fonts";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Brainlens Starter Kit",
	description: "Generated by brainlens starter kit",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={cn("font-sans", geist.variable)}>
			<body
				className={cn("antialiased", geistSans.variable, geistMono.variable)}
			>
				{children}
			</body>
		</html>
	);
}
